const PHOTOS_COUNT = 25;
const MIN_COMMENTS_PER_PHOTO = 1;
const MAX_COMMENTS_PER_PHOTO = 10;
const MAX_COMMENTS_TOTAL = 1000;

export {
  PHOTOS_COUNT,
  MIN_COMMENTS_PER_PHOTO,
  MAX_COMMENTS_PER_PHOTO,
  MAX_COMMENTS_TOTAL
};
