const PHOTOS_COUNT = 25;

const MIN_COMMENTS_PER_PHOTO = 1;
const MAX_COMMENTS_PER_PHOTO = 15;
const MAX_COMMENTS_TOTAL = 1000;
const DISPLAY_COMMENTS_STEP = 5;

const MAX_HASHTAGS_COUNT = 5;
const MIN_HASHTAG_LENGTH = 2;
const MAX_HASHTAG_LENGTH = 20;

const MAX_DESCRIPTION_LENGTH = 140;

const IMG_SCALE_CHANGE_STEP = 25;
const IMG_MIN_SCALE = 25;
const IMG_MAX_SCALE = 100;

export {
  PHOTOS_COUNT,
  MIN_COMMENTS_PER_PHOTO,
  MAX_COMMENTS_PER_PHOTO,
  MAX_COMMENTS_TOTAL,
  DISPLAY_COMMENTS_STEP,
  MAX_HASHTAGS_COUNT,
  MAX_DESCRIPTION_LENGTH,
  MIN_HASHTAG_LENGTH,
  MAX_HASHTAG_LENGTH,
  IMG_SCALE_CHANGE_STEP,
  IMG_MIN_SCALE,
  IMG_MAX_SCALE
};
